title: nocaps
email: kdexd@gatech.edu
description: Towards image captioning in the wild.
  ---
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://nocaps.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['_pages']
